-- CREATE DATABASE - CRIA UM BANCO
CREATE 
	DATABASE bercario; 

-- DROP DATABASE - DELETA UM BANCO
DROP 
	DATABASE bercario;
-- USE - UTILIZA UM BANCO PARA REALIZAR AS OPERAÇÕES
USE bercario;

-- CREATE TABLE - CRIA UMA TABELA NO BANCO	
-- PRIMARY KEY - DIZ QUE AQUELE ATRIBUTO É A CHAVA PRIMARIA
-- AUTO INCREMENT - DIZ QUE AQUELE ATRIBUTO AUMENTA O NÚMERO AUTOMATICAMENTE
-- NOT NULL - DIZ QUE AQUELE ATRIBUTO DEVE SER PREENCHIDO, NÃO PODE ESTAR VAZIO
-- UNIQUE - DIZ QUE SÓ PODE TER UM DAQUELE RESGISTRO NA TABELA
CREATE TABLE tb_mae(
	cod_mae INT PRIMARY KEY AUTO_INCREMENT,
    nome_mae VARCHAR(255) NOT NULL,
    telfone_mae VARCHAR(20),
    email_mae VARCHAR(20) UNIQUE
);

CREATE TABLE tb_medico(
	id_medico INT PRIMARY KEY AUTO_INCREMENT,
    crm VARCHAR(10) DEFAULT '123456-ES',
    nome VARCHAR(255) NOT NULL
);

-- ALTER - ALTERA ALGO EXISTENTE
-- ADD - ADICIONA COLUNAS A UMA TABELA EXISTENTE
ALTER TABLE tb_medico
ADD especialidade ENUM("GERAL","PEDIATRA","OBSTETRA");

-- DROP COLUMN - DELETA UMA COLUNA DE UMA TABEA EXISTENTE
ALTER TABLE tb_medico
DROP COLUMN especialidade;

-- MODIFY - MODIFICA UMA COLUNA DE UMA TABELA EXISTENTE 
ALTER TABLE tb_medico
MODIFY COLUMN especialidade VARCHAR(255);

-- DROP TABLE - DELETA UMA COLUNA DE UMA TABEA EXISTENTE
DROP TABLE tb_medico;

CREATE TABLE tb_bebe(
id_bebe INT PRIMARY KEY AUTO_INCREMENT,
nome_bebe VARCHAR(255),
dt_nasc DATE,
hr_nasc TIME,
peso DECIMAL(6,4),
cod_mae INT,
id_medico INT,
-- REFERENCIANDO AS CHAVES ESTRANGEIRAS
FOREIGN KEY (cod_mae) REFERENCES tb_mae(cod_mae),
FOREIGN KEY (id_medico) REFERENCES tb_medico(id_medico)
);

